### Update an existing patient entity
PUT http://localhost:4000/patients/a5e6da39-808d-480e-906c-4c9bac343669
Content-Type: application/json

{
  "name": "Chamith Dilshan",
  "email": "isabella.walker@example.com",
  "address": "132/testAddress",
  "dateOfBirth": "1990-12-12"
}

###